config/routes.rb
Rails.application.routes.draw do

  get '/', to: "rides#index"
  
  get '/customerapp.html', to: 'rides#new'
  post 'request_ride', to: 'rides#create'

  get '/driverapp.html', to: 'drivers#home', as: "driver_home"
  post '/accept_ride', to: 'drivers#accept_ride'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :rides
end

app/models/driver.rb
class Driver < ActiveRecord::Base
  has_many :rides
end

app/models/ride.rb
class Ride < ActiveRecord::Base
  belongs_to :customer
  belongs_to :driver

  scope :waiting, -> { where(status: 'waiting') } #ideally the way status should be stored should be with some agreed convention
  scope :ongoing, -> { where(status: 'ongoing') }

  def self.fetch_waiting_and_driver_rides( driver_id )
    Ride.select("id, customer_id, request_time, pickup_time, status").where("driver_id IS NULL OR driver_id = ?", driver_id).includes(:customer).group_by(&:status)
  end

  def self.fetch_all_rides
    Ride.select("id, customer_id, request_time, pickup_time, status").includes(:customer).group_by(&:status)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController

  before_action :fetch_driver
  before_action :check_if_ongoing_ride_present, only: [ :accept_ride ]

  def home
    @rides = Ride.fetch_waiting_and_driver_rides( @driver.id ) if @driver.present?
  end

  def accept_ride
    begin
      if !@cant_accept
        ride = Ride.find_by_id( params[:ride_id] )
        if ride.status == "waiting"
          ride.update_attributes( driver_id: @driver.id, status: "ongoing", pickup_time: Time.now )
          flash[:success] = "Successfully Accepted the Ride!"
        else
          flash[:notice] = "Oops! Some other driver already accepted it"
        end
      end
      redirect_to driver_home_path(id: @driver.id)

    rescue Exception => e
      respond_to do |format|
        logger.error "There was some code error in drivers#accept_ride. " + e.message + " " + Time.zone.now.strftime("%H:%M:%S - %d/%m/%Y").to_s
        flash[:error] = "Please try again later."
        redirect_to driver_home_path(id: @driver.id)
      end      
    end
  end

  def fetch_driver
    @driver = Driver.find_by_sys_id( params[:id] )
    if @driver.blank?
      @cant_accept = true
      flash[:error] = "Please give correct driver's id"
    end
  end

  def check_if_ongoing_ride_present
    if ( @driver.present? and @driver.rides.ongoing.count > 0 )
      @cant_accept = true
      flash[:notice] = "Please complete your ongoing ride before accepting"
    end
  end

end

app/controllers/rides_controller.rb
class RidesController < ApplicationController

  before_action :find_or_create_customer, only: [ :create ]
  before_action :check_if_rides_available, only: [ :create ]

  def index
    #TODO - Pagination
    @rides = Ride.fetch_all_rides
  end

  def new
  end

  def create
    begin
      ride = @customer.rides.create( status: "waiting", request_time: Time.now )

      respond_to do |format|
        format.json { render :json => { :success => true, :status => 200 } }
      end
    rescue Exception => e
      respond_to do |format|
        logger.error "There was some code error in rides#create. " + e.message + " " + Time.zone.now.strftime("%H:%M:%S - %d/%m/%Y").to_s
        format.json { render :json => { :success => false, :user_message => "Please try again later.", :status => 500 } }
      end      
    end 
  end

  def find_or_create_customer
    if params[:sys_id].present?
      @customer = Customer.find_or_create_by( sys_id: params[:sys_id] )
    else
      render :json => { :success => false, :user_message => "Please enter customer id", :status => 400 } 
    end
  end

  def check_if_rides_available
    #allow rides only if there are less than 10 waiting rides
    render :json => { :success => false, :user_message => "Rides not available. Please try again later", :status => 200 } if Ride.waiting.count >= 10
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/drivers/home.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>
<% if @driver.present? %>
  <h3><button type="button" style="background-color: #4CAF50"><b><%= link_to "Refresh", driver_home_path(id: @driver.id) %></b></button></h3>
  <% if @rides.present? %>
    <% if @rides["waiting"].present? %>
      <div>
        <h3><%= "Waiting Rides" %></h3>
          <table border="1">
            <tr>
              <td><b>Req Id</b></td>
              <td><b>Cust Id</b></td>
              <td><b>Request Time</b></td>
              <td><b>Action</b></td>
            </tr>
            <% @rides["waiting"].each do |ride| %>
              <tr>
                <td><%= ride.id %></td>
                <td><%= ride.customer.sys_id %></td>
                <td><%= "#{((Time.now - ride.request_time)/60).to_i} min ago" %></td>
                <td><%= link_to "Select", accept_ride_path(id: @driver.id, ride_id: ride.id), method: :post %>
              </tr>
            <% end %>
          </table>
      </div>
    <% end %>

    <% if @rides["ongoing"].present? %>
      <div>
        <h3><%= "Ongoing Rides" %></h3>
          <table border="1">
            <tr>
              <td><b>Req Id</b></td>
              <td><b>Cust Id</b></td>
              <td><b>Request Time</b></td>
              <td><b>Picked Up</b></td>
            </tr>
            <% @rides["ongoing"].each do |ride| %>
              <tr>
                <td><%= ride.id %></td>
                <td><%= ride.customer.sys_id %></td>
                <td><%= "#{((Time.now - ride.request_time)/60).to_i} min ago" %></td>
                <td><%= "#{((Time.now - ride.pickup_time)/60).to_i} min ago" %></td>
              </tr>
            <% end %>
          </table>
      </div>
    <% end %>

    <% if @rides["complete"].present? %>
      <div>
        <h3><%= "Complete Rides" %></h3>
          <table border="1">
            <tr>
              <td><b>Req Id</b></td>
              <td><b>Cust Id</b></td>
              <td><b>Request Time</b></td>
              <td><b>Picked Up</b></td>
              <td><b>Completed</b></td>
            </tr>
            <% @rides["complete"].each do |ride| %>
              <tr>
                <td><%= ride.id %></td>
                <td><%= ride.customer.sys_id %></td>
                <td><%= "#{((Time.now - ride.request_time)/60).to_i} min ago" %></td>
                <td><%= "#{((Time.now - ride.pickup_time)/60).to_i} min ago" %></td>
                <td><%= "#{((Time.now - ride.pickup_time)/60).to_i - 5} min ago" %></td>
              </tr>
            <% end %>
          </table>
      </div>
    <% end %>

  <% else %>
    <h3> No Rides Present. </h3>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaxiApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/rides/index.html.erb
<% if @rides.present? %>
  <table border="1">
    
    <tr>
      <td><b>Req Id</b></td>
      <td><b>Cust Id</b></td>
      <td><b>Request Time</b></td>
      <td><b>Status</b></td>
    </tr>

    <% if @rides["waiting"].present? %>
      <% @rides["waiting"].each do |ride| %>
        <tr>
          <td><%= ride.id %></td>
          <td><%= ride.customer.sys_id %></td>
          <td><%= "#{((Time.now - ride.request_time)/60).to_i} min ago" %></td>
          <td style="color:red"><%= ride.status %>
        </tr>
      <% end %>
    <% end %>

    <% if @rides["ongoing"].present? %>
      <% @rides["ongoing"].each do |ride| %>
        <tr>
          <td><%= ride.id %></td>
          <td><%= ride.customer.sys_id %></td>
          <td><%= "#{((Time.now - ride.request_time)/60).to_i} min ago" %></td>
          <td style="color:green"><%= ride.status %>
        </tr>
      <% end %>
    <% end %>

    <% if @rides["complete"].present? %>
      <% @rides["complete"].each do |ride| %>
        <tr>
          <td><%= ride.id %></td>
          <td><%= ride.customer.sys_id %></td>
          <td><%= "#{((Time.now - ride.request_time)/60).to_i} min ago" %></td>
          <td style="color:blue"><%= ride.status %>
        </tr>
      <% end %>
    <% end %>

  </table>
<% else %>
  <h3> No Rides Present. </h3>
<% end %>

app/views/rides/new.html.erb
<%= form_tag( request_ride_path(format: "json"), :method =>"POST" ) do %>
  <%= label_tag(:id, "Customer Id") %>: 
  <%= text_field_tag :sys_id %><br/><br/>       
  <%= submit_tag "Ride Now" %>
<% end %>